docs: server functions
BuilderIO/qwik pull request #2722
Opened 2023-01-26 12:21 UTC by manucorporat

2023-01-27 00:50 UTC, VinSpee commented on packages/docs/src/routes/qwikcity/endpoints/index.md
> +  throw json(200, { hello: 'world' });
Is the new syntax to actually `throw` each of these (`text`, `json`, etc?)

2023-01-27 01:05 UTC, VinSpee requested changes
Some typos / tweaks to wording. I’m very excited about these docs / the upcoming release, looking good!

2023-01-27 01:05 UTC, VinSpee commented on packages/docs/src/routes/qwikcity/loader/index.md
> +This information comes handly when the loaders needs to conditionally return data based on the request, or it needs to override the response status, headers or body manually.
```suggestion
This information comes in handy when the loader needs to conditionally return data based on the request, or it needs to override the response status, headers or body manually.
```

2023-01-27 01:05 UTC, VinSpee commented on packages/docs/src/routes/qwikcity/loader/index.md
> +You should not use a loader to create a REST API, for that you better use a [Endpoint](/qwik-city/), which allows you to have tight control over the response headers and body.
```suggestion
You should not use a loader to create a REST API, for that you’d be better off using an [Endpoint](/qwik-city/), which allows you to have tight control over the response headers and body.
```

2023-01-27 11:29 UTC, manucorporat commented
Thanks for the review! unfortunately i am moving so many things, i cant apply the feedback!
I will get it to a much better spot today

2023-02-04 20:32 UTC, Futhark commented on packages/docs/src/routes/qwikcity/loader/index.mdx
> +The behave like RPC server-side functions that can be invokated by Qwik Components during rendering.
The -> They?

2023-02-07 18:12 UTC, merged