Add Error Serializers for custom and nested errors
BuilderIO/qwik pull request #3380
Opened 2023-03-15 08:42 UTC by n8sabes

# What is it?

- [X] Feature / enhancement
- [X] Bug
- [ ] Docs / tests

# Description

This PR enables the serialization and deserialization of Error objects and Custom Error objects, extracting only primitive values and rebuilding nested Error objects as necessary.

The `serializeError` function takes an Error or Custom Error object as input and clones its primitive values using the `cloneErrorPrimitives` function before returning the resulting object in a JSON string format.

The `deserializeError` function takes a serialized Error object string as input and converts it back into an Error or Custom Error object with only the necessary primitive values. It accomplishes this by parsing the input string into an object, extracting the needed values and creating a new Error object with those values. If the input string contains nested Error objects, it will rebuild them by calling the `deserializeDeepErrors` function.

The `cloneErrorPrimitives` function recursively extracts all primitive values from an object or array, including handling of circular references, pruning the stack trace from Error objects, and returning a new object with only primitive values. This function is called by `serializeError` to extract the necessary values from the Error object.

Finally, the `deserializeDeepErrors` function rebuilds any nested Error objects that were serialized. It takes the rebuilt Error objects and inserts them back into the appropriate locations within the parent Error object.

# Use cases and why

Custom errors or extended error information is not supported with the current serializer. Custom errors are necessary when working with many backend systems.

# Checklist:

- [X] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [1/2 ] Added new tests to cover the fix / functionality

Validation object provided.

2023-03-15 09:03 UTC, n8sabes commented
<h3>Test File</h3>
Here is an `index.tsx` test file that exercises the serializer. I have also used it in a staged system through `server$` boundaries.

```typescript
import { $, component$ } from '@builder.io/qwik';
import { deserializeError, serializeError } from '~/utils/errorSerializer';


class CustomError extends Error {
  custom: any;

  constructor(message: string, custom?: any) {
    super(message);
    this.custom = custom;
  }
}

export default component$(() => {

  const simpleErrorTest = $(() => {
    const xErr = new CustomError("Deep X-Error!", 1234);
    const serErr = serializeError(xErr);
    console.log("serErr:", serErr);
    const desErr = deserializeError(serErr);
    console.log("desErr:", desErr);
    console.log("desErr:", JSON.stringify(desErr));
  });

  const deepErrorTest = $(() => {
    const validate = {
      e1: new Error("Standard Error"),
      c: {},
      o: {
        e2: new CustomError("Custom Error", {
          e3: new Error("Super Deep Standard Error"),
        }),
        c: {},
        stack: "keep me",
        n: null,
        b: true,
        v: 123,
        s: "abc",
        u: undefined,
        f: () => "function!",
      },
      stack: "keep me",
      n: null,
      b: true,
      v: 123,
      s: "abc",
      u: undefined,
      f: () => "function!"
    };
    validate.c = validate;
    validate.o.c = validate;

    const xErr = new CustomError("Deep Error!", validate);
    const serErr = serializeError(xErr);
    console.log("serErr:", serErr);
    const desErr = deserializeError(serErr);
    console.log("desErr:", desErr);
    console.log("desErr:", JSON.stringify(desErr));
  });

  return (<div>
    <h1>Test Error Serialization</h1>
    <p>Serialize errors to JSON and back again. Stack and functions are not serialized and prevents circular reference.</p><br />
    <button onClick$={simpleErrorTest}>Simple Error Test</button><br /><br />
    <button onClick$={deepErrorTest}>Deep Error Test</button>
  </div>);
})
```

2023-03-15 20:08 UTC, zanettin commented
Hey Sebastian 👋 
CI complains atm because `pnpm fmt` needs to be exec 👼 thanks for this PR 🙏

2023-03-16 00:54 UTC, n8sabes commented
Thanks @zanettin, didn't realize `pnpm fmt` was a thing. Updated the checkin.

I have Prettier installed, but I can't figure out why it formats some `.ts` files with two indents and others with four. I have vscode defaults set to Prettier, even. It drives me crazy.

2023-03-16 06:00 UTC, n8sabes commented
@manucorporat, I have added **Dynamic Error** Class generation during deserialization so that the `constructor.name` comes through.

2023-03-16 08:21 UTC, manucorporat commented
This is amazing work! i am a little concerned about the amount runtime added just to solve this issue, need to run it with the team

2023-03-17 04:53 UTC, n8sabes commented
<h2>OPTIMIZED -- PERF NOW SAME AS OLD OPTIMIZER FOR NATIVE ERRORS!</h2>

@manucorporat, thanks for the comment. I've gone back and reviewed the new error serializer, and in several places heavily optimized it to perform as well as the old serializer. The added advantage of this is it now support custom errors and deep object errors. -- Please take a looks. There may be was to further optimize it, and welcome you throughs. Please see the attached screenshot of benchmarks from test page (above).
![New Error Serializer Test Results](https://user-images.githubusercontent.com/10445528/225815768-58007772-f53e-4bcb-96de-7330fe6ad34d.png)

2023-03-17 08:20 UTC, n8sabes commented
<h2>OPTIMIZED PERFORMANCE</h2>
<h3>EQUAL TO OLD OPTIMIZER WITH BETTER NATIVE AND CUSTOM ERROR SUPPORT</h3>

@manucorporat, I've gone back and reviewed the new error serializer and optimized it to perform as well as the old serializer *(maybe a bit better)*. The added advantage of this is it now supports custom errors and deep error objects (like from GraphQL errors). There may be ways to further optimize it and welcome you throughs.  Classnames were not possible without evaluating a class inline which would be unsafe but `prototype.name` work well now. 

Please see the attached screenshot of benchmarks run with the test page provided. The page also has tests that can be migrated to a unit test.

![New Error Serializer Test Results](https://user-images.githubusercontent.com/10445528/225848825-898f5b2f-33e6-41e7-a84b-3ebccca67444.png)

2023-03-17 20:01 UTC, n8sabes commented
<h2> New Error Serializer Test on StackBlitz </h2>

[New Error Serializer Test on StackBlitz](https://stackblitz.com/edit/qwik-starter-vuzfrv?file=src/routes/index.tsx)

![New Error Serializer Test Results](https://user-images.githubusercontent.com/10445528/226019477-70b1120e-3f60-4455-9b59-f26788eb8185.png)

2023-03-19 16:51 UTC, n8sabes commented
<h1>NEW: Deep Error Mitigation</h1>
I had an idea to further optimize error serialization. In version 2, the error serializer **always** mitigates what error data is send back. A developer may not realize a custom error could have additional objects and there is no point in transferring them if they are not to be consumed.

To transfer errors with custom fields or deep objects, such as in GraphQL, the developer must add the `__qDeep` flag to the error object. If this flag is present, only then will the error with custom fields/objects be serialized over the wire. The `__qDeep` flag is automatically be stripped out during the deserialization process.

I have updated the StackBlitz ( [HERE](https://stackblitz.com/edit/qwik-starter-vuzfrv) ) with both versions to explore, but think I like Version 2 better to avoid unnecessary data serialization.

2023-05-07 04:12 UTC, tasawar-hussain requested changes

2023-05-07 04:12 UTC, tasawar-hussain commented on packages/qwik/src/core/error/error_serializer.ts
> +      if (deepErrObj.__qName) {
```suggestion
    if (objKey && deepErrObj.__qName) {
```

2023-05-07 04:12 UTC, tasawar-hussain commented on packages/qwik/src/core/error/error_serializer.ts
> +        stack;
```suggestion
```

2023-08-27 07:26 UTC, closed without merging