QRL::bind() is QRL / Issue2972 rewritten
BuilderIO/qwik pull request #4224
Opened 2023-05-14 21:17 UTC by mesterum

# Overview

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

[PR for issue: 4223](https://github.com/BuilderIO/qwik/issues/4223)

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] Replaced the Issue2972 test with mine

2023-05-15 07:46 UTC, mesterum commented
I admit that this solution is half baked. It doesn’t hold over the wire. The bind arguments must be captured too.

2023-06-30 16:31 UTC, mhevery commented on packages/qwik/src/core/qrl/qrl-class.ts
> +  const qrl = Object.setPrototypeOf(invokeQRL, methods);
Why do we have to do this? This has a big performance penalty.: https://stackoverflow.com/questions/52654781/why-does-using-object-setprototypeof-impact-performance-heavily

2023-06-30 16:40 UTC, mhevery requested changes
1. It introduces a negative performance of using `Object.setProtypeOf`
2. It will not survive serialization over the wire.

2023-06-30 16:40 UTC, mhevery commented
If there is no progress on this PR in the next few weeks, I would suggest closing it.

2023-07-04 15:56 UTC, mesterum commented
I didn’t know about the penalty of using Object.setPrototypeOf(). Using
Object.create() is not possible be instead of the last line because the qrl
must be a callable function.
Why do I want the methods be in the prototype chain(PC). Because the
f.bind(…args) function creates another function with all the PC of f. If
methods object is not in PC of qrl, it will be not in qrl.bind().



On Fri, Jun 30, 2023 at 7:31 PM Miško Hevery ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In packages/qwik/src/core/qrl/qrl-class.ts
> <https://github.com/BuilderIO/qwik/pull/4224#discussion_r1248066826>:
>
> > @@ -159,7 +159,9 @@ export const createQRL = <TYPE>(
>      $captureRef$: captureRef,
>      dev: null,
>    };
> -  const qrl = Object.assign(invokeQRL, methods);
> +  Object.setPrototypeOf(methods, Function.prototype)
> +  seal(methods)
> +  const qrl = Object.setPrototypeOf(invokeQRL, methods);
>
> Why do we have to do this? This has a big performance penalty.:
> https://stackoverflow.com/questions/52654781/why-does-using-object-setprototypeof-impact-performance-heavily
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BuilderIO/qwik/pull/4224#pullrequestreview-1507522938>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQN3HVAO74I2WZQ7K3HKH3XN35OVANCNFSM6AAAAAAYBMOZRU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-04 15:59 UTC, mesterum commented
1.
   2. It will not survive serialization over the wire.

I don’t know how to do it.

On Fri, Jun 30, 2023 at 7:40 PM Miško Hevery ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
>    1. It introduces a negative performance of using Object.setProtypeOf
>    2. It will not survive serialization over the wire.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BuilderIO/qwik/pull/4224#pullrequestreview-1507537869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQN3HUHC7VEH2M2CUO2XCTXN36O5ANCNFSM6AAAAAAYBMOZRU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-09 09:24 UTC, closed without merging