Dark theme support in Qwik
BuilderIO/qwik pull request #5255
Opened 2023-10-02 10:05 UTC by Inaam-Ur-Rehman

# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [x ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ x] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2023-10-02 22:42 UTC, mhevery requested changes
Also let me know when this is ready for full review.

2023-10-02 22:42 UTC, mhevery commented on packages/docs/src/routes/docs/cookbook/Theme Management/index.mdx
> +##Problem
Missing front matter.

2023-10-08 05:54 UTC, Inaam-Ur-Rehman reviewed
Updated the frontmatter

2023-10-10 16:58 UTC, mhevery approved these changes

2023-10-10 16:59 UTC, merged

2023-10-10 19:54 UTC, Inaam-Ur-Rehman reviewed
There is typo in the contributor name. Can I change it

2023-10-10 20:05 UTC, gioboa commented
@Inaam-Ur-Rehman yes, you must create a new PR for that.