fix:(core) Fill the holes of the sparse array with `undefined`
BuilderIO/qwik pull request #5336
Opened 2023-10-20 16:59 UTC by genki

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

To fix the issue #5333 fill the holes of the sparse array with `undefined` in order to serialize any arrays.

# Use cases and why

Please see the issue #5333 

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2023-10-21 16:45 UTC, mhevery requested changes
- Could we have a test for this?
- I noticed fuel on above. There is a comment that specifically says to check for a raise with holes, but then we fill it in, so I think the common needs to change.

2023-10-21 17:10 UTC, genki commented
@mhevery I couldn't find the tests that are checking to raise error when with holes.
It's okay that simply remove the comment line and add a test to check if the sparse array doesn't raise the error?

2023-10-21 17:41 UTC, wmertens commented
This feels pretty hacky IMHO. Wouldn't it be better to support sparse arrays in the serializer?

2023-10-21 21:19 UTC, genki commented
@wmertens I think so too, but the `JSON.stringify()` does equivalent thing. This may be the JavaScript's way.

2023-10-22 12:56 UTC, wmertens commented
There's two problems:
- (minor) we change a data structure given to us
- (major) we allow the dev to write `a[100000]=1` and then we're invisibly serializing 100000x `undefined`

I prefer having the dev consider their options over this approach.

2023-10-23 12:39 UTC, mhevery commented
Thinking more about this, I think arrays with holes are very bad for performance anyway and should be discouraged. Why can't the developer just fix their code?

2023-10-24 07:57 UTC, genki commented
I think there is no one to use the sparse array intentionally but it could be mixed in if using outer APIs that use it.
Even though, we application engineer can fill the holes in advance. And Qwik can do as well.
The problem is which one do it.

2023-10-24 08:10 UTC, genki commented
Qwik has been checking all arrays if they have holes. Filling them at that time can be taken with minimal cost.
If we have applications done it, it introduced extra cost to check the arrays if they have holes twice.

2023-10-24 14:57 UTC, mhevery commented
I agree that it is minimal effort, but it is not the same thing. Arguably filling in the array changes the meaning of the application....

```
> a = [];
[]
> a[1] = 123
123
> Array.prototype[0] = 'WEIRD'
'WEIRD'
> a[0]
'WEIRD'
```

So I don't think we should be doing it.

I think the correct thing is to either:
1. Error (as we do now)
2. Serialize the array with holes and then re-create the holes.


Arguably holy arrays are just bad practice, so I think Erroring is probably a better solution...

2023-10-24 17:12 UTC, genki commented
Haha, I have never think there could be someone who changes the `Array.prototype[0]` :)
Okey, I will choose to fill the holes by myself. It might be the best for people who believe there may be sparse array but no one change the `Array.prototype`
Thank you for conversation about it that brings me forward :)

2023-10-24 17:12 UTC, closed without merging