chore: Add Docker example to Node deployment
BuilderIO/qwik pull request #5605
Opened 2023-12-18 18:45 UTC by nelsonprsousa

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests / types / typos

# Description

Added a doc section on how to run a Qwik app using Docker.

# Checklist:

- [X] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2023-12-18 20:30 UTC, gioboa commented
Thanks @nelsonprsousa for your help. I love the idea to share a Dockerfile example.
My only concerns is that this is more a cookbook example. Can you move your code [there](https://qwik.builder.io/docs/cookbook/)?
We can mention this example in the node deployments page though

2023-12-18 20:31 UTC, gioboa requested changes
Thanks @nelsonprsousa for your help. I love the idea to share a Dockerfile example.
My only concerns is that this is more a cookbook example. Can you move your code [there](https://qwik.builder.io/docs/cookbook/)?
We can mention this example in the node deployments page though

2023-12-18 20:32 UTC, mhevery approved these changes

2023-12-18 20:32 UTC, mhevery commented
+1 for moving to cookbook.

2023-12-24 19:43 UTC, gioboa commented
@nelsonprsousa do you have any news for this one?

2023-12-26 01:28 UTC, nelsonprsousa commented
> @nelsonprsousa do you have any news for this one?

Still on my _todo_ list. Once the festives are over count on me to close this one 👍

2023-12-28 00:15 UTC, nelsonprsousa commented
> @nelsonprsousa do you have any news for this one?

Feel free to give some feedback.

cc @mhevery @gioboa

2023-12-28 08:03 UTC, gioboa requested changes

2023-12-28 08:03 UTC, gioboa commented on packages/docs/src/routes/docs/cookbook/index.mdx
> +- [Deploy with Node using Docker](./node-docker-deploy)
You need to add this page in this file too
`qwik/packages/docs/src/routes/docs/menu.md`
Thanks

2023-12-28 16:14 UTC, nelsonprsousa commented on packages/docs/src/routes/docs/cookbook/index.mdx
> +- [Deploy with Node using Docker](./node-docker-deploy)
Done and done, can you please check? 🙏

2023-12-28 16:15 UTC, nelsonprsousa commented on packages/docs/src/routes/docs/cookbook/node-docker-deploy/index.mdx
> +---
Most of the other cookbook docs do not have that. However I added on the new one.

Can you please check? 🙏

2023-12-28 16:16 UTC, nelsonprsousa commented on packages/docs/src/routes/docs/cookbook/node-docker-deploy/index.mdx
> + ```
Did my best. Would like to receive some feedback.

2023-12-28 16:22 UTC, gioboa commented on packages/docs/src/routes/docs/cookbook/node-docker-deploy/index.mdx
> + ```
That's awesome, your rock 🚀

2023-12-28 18:40 UTC, gioboa requested changes

2023-12-28 18:41 UTC, gioboa commented on packages/docs/src/routes/docs/cookbook/node-docker-deploy/index.mdx
> +This Dockerfile is used to build a Docker image for our Qwik Node.js application. You can edit it accordingly to use npm, pnpm or bun.
With this little change I think will be perfect 😊

2023-12-28 19:01 UTC, nelsonprsousa commented on packages/docs/src/routes/docs/cookbook/node-docker-deploy/index.mdx
> +This Dockerfile is used to build a Docker image for our Qwik Node.js application. You can edit it accordingly to use npm, pnpm or bun.
Just added a phrase saying that, as sugeested. We can in the future add more examples for other package managers if this isn't enough 👍

2023-12-28 20:53 UTC, gioboa commented
The menu label was too long, I fixed it.
<img width="247" alt="Screenshot 2023-12-28 at 21 46 44" src="https://github.com/BuilderIO/qwik/assets/35845425/8dd7024d-cfc5-4c7c-8f59-b5d27294edfb">

2023-12-28 20:54 UTC, gioboa approved these changes
Thanks @nelsonprsousa

2023-12-28 20:55 UTC, nelsonprsousa commented
> The menu label was too long, I fixed it. <img alt="Screenshot 2023-12-28 at 21 46 44" width="247" src="https://private-user-images.githubusercontent.com/35845425/293272913-8dd7024d-cfc5-4c7c-8f59-b5d27294edfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3OTcxNzgsIm5iZiI6MTcwMzc5Njg3OCwicGF0aCI6Ii8zNTg0NTQyNS8yOTMyNzI5MTMtOGRkNzAyNGQtY2ZjNS00YzdjLThmNTktYjVkMjcyOTRlZGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIwNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMjVjNjk0MjE5NTVlMzNkY2Y2YTEzZDE4ZTY5Njk1OGY1NGMxMjE3MzhlMjBjZGVjMDQwMmEyNDQzMjQ5YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RF549Y5GFRD1XauAifSoRVQ81oHUb7KQSpHBPKCNaVI">
> 
> <img alt="Screenshot 2023-12-28 at 21 53 28" width="207" src="https://private-user-images.githubusercontent.com/35845425/293273526-d29b35ea-7963-4611-a080-8514d98d8660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3OTcxNzgsIm5iZiI6MTcwMzc5Njg3OCwicGF0aCI6Ii8zNTg0NTQyNS8yOTMyNzM1MjYtZDI5YjM1ZWEtNzk2My00NjExLWEwODAtODUxNGQ5OGQ4NjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIwNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MjUwYjFiOTU1NDQwMmJhMTY5ZWM0OWRmMmQyNWQ1M2M0ZmMxMGU5YjA5ZTdlNTkxNmM1N2U1N2ExZmJmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.83XV9c9vGHjzIGdvVzhOWZdwO-PyoMdtwOTkeBFkUx0">

Thanks. I am not aware on how to check a preview of the website?

2023-12-28 21:01 UTC, merged

2023-12-28 21:18 UTC, gioboa commented
From the root  install the dependencies and run
```
pnpm docs.dev
```
👍

2023-12-29 16:26 UTC, gioboa commented
Yes, it is. You need to change yarn with bun and use the bun adapter to build your app