Feat optional param
BuilderIO/qwik pull request #5632
Opened 2023-12-23 15:52 UTC by samyung0

# Overview

Adds optional param for route matching

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Draft Sytax: `[param.]`

This is my ever first pull request and I apologize if I messed anything up.

Currently `[...param]` matches zero or more than 1 segments while [param] matches exactly one segment. This might not cover all the use cases. Suppose I am integration i18n into my app and I put all routes under `[...lang]`. Then `/`, `/en-US/`, etc are all valid routes and works perfectly. However, visiting an invalid route will also be rendered by `[...lang]/index.tsx` instead of showing the 404 page.

One of the solution is to use `[lang]` instead of [...lang] and redirect `/` to a default locale but redirecting home page seems a bit sketchy to me (maybe implications towards SEO?).

Second solution is to analyze the path in `[...lang]/index.tsx`, if the first segment is not a supported locale, then throw a redirect or error. I haven't tested this yet but it seems like a workaround instead of a good solution.

 The current draft for the optional param syntax is `[lang.]` and it matches exactly one or zero path segment. With optional param, any invalid route with more than 1 segment will render the 404 page without having to manually check the path.

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-01-11 13:02 UTC, wmertens commented
I suppose this could be useful although the language usecase is not as hard as you make it out to be https://github.com/wmertens/compiled-i18n/blob/HEAD/qwik.md#route-based-locale-selection

In any case I'm not sure of the syntax, because `[...params]` means that `params` is a variable name, and `[lang.]` means the word "lang" might be in there.

2024-01-12 00:06 UTC, samyung0 commented
Sorry for the confusion, [lang.] means that a param named lang might be there, I can change the name to [param.] and the name will change to param.
I do agree that i11n is not the best example here since mostly people make the [lang] part required instead of optional anyway, but I hope this can be useful in some other ways :)

2024-01-12 08:21 UTC, wmertens commented
Oh hmm, so it's a wildcard match on anything, and if there's not enough path to do the match, it is left out?

That seems like it might cause subtle bugs, no?

I'd like to postpone this until we have a real usecase.

Also, how about this syntax: `<string or [param]>[0,1]` ?

2024-01-12 15:23 UTC, samyung0 commented
I agree to leave it open until there is a real use case that requires it. Currently the matching route fn will try to match the route _without_ the [param.] first before going back to matching the route with the param. It also takes precedence over catchall routes. It could introduce some subtle bugs but unlikely, but I am totally fine with leaving it open at the moment.

2024-01-17 07:06 UTC, wmertens commented
Paging @mhevery to weigh in on the API implications

2024-01-17 08:29 UTC, wmertens requested changes
marking this as Change Requested because the syntax isn't ok right now and we're not sure if we want to add it.

2024-03-04 10:20 UTC, wmertens commented
I'm going to close this for now to keep the PR list relevant.

If a usecase pops up, it should be findable in the closed PR list.

2024-03-04 10:20 UTC, closed without merging