(adapt) feat aws
BuilderIO/qwik pull request #5732
Opened 2024-01-18 08:36 UTC by leifermendez

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-01-18 14:22 UTC, leifermendez commented
@wmertens @zanettin

2024-01-18 15:55 UTC, wmertens commented
@leifermendez Great! My only question is, why does qwik-city need the extra dependencies?

2024-01-18 16:30 UTC, wmertens requested changes
Looks great, but I think serverless-http is actually not needed now? I don't see it being imported.

Likewise for the source-map-support

2024-01-19 17:25 UTC, wmertens commented on starters/adapters/aws-lambda/src/entry_aws-lambda.tsx
> -import serverless from "serverless-http";
since you remove this, I suppose it can go from the package.json too? And I think the two other serverless packages aren't needed anymore either?

2024-01-19 18:49 UTC, wmertens approved these changes
Woohoo 🙌

2024-01-19 19:01 UTC, merged