fix: docs.dev script locally
BuilderIO/qwik pull request #5750
Opened 2024-01-23 19:17 UTC by balaji-sivasakthi

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-01-23 19:38 UTC, Balastrong requested changes
Hey @balaji-sivasakthi, have you tested it? I tried to delete the qwik folder and restart the process (`pnpm install` and `pnpm docs.dev`) but it still misses some packages, in this case the error is on `qwik-labs`.

```
failed to load config from /Users/leonardo/PersProgetti/qwik/packages/docs/vite.config.ts
error when starting dev server:
Error: Cannot find module '/Users/leonardo/PersProgetti/qwik/packages/docs/node_modules/@builder.io/qwik-labs/vite/index.js'
```

Besides, I don't think adding a long build command each time the dev command is launched is a good idea (in any case I'd not put it in the global `package.json` but rather in `packages/docs/package.json`)

What do you think?

2024-01-23 19:50 UTC, balaji-sivasakthi commented
@Balastrong  I haven't tested it properly yet. @wmertens mentioned that there might be issues because of build.dev, so I added it. I will make a new commit to address this by writing custom script files that check and validate the build core and other missing modules. I'll take care of that.

2024-01-23 19:54 UTC, gioboa commented
A `postinstall` script that build packages could make it works

2024-01-23 19:56 UTC, balaji-sivasakthi commented
` I tried to delete the qwik folder and restart the process (pnpm install and pnpm docs.dev) but it still misses some packages, in this case the error is on qwik-labs.`

I've tried this case works for me.

2024-01-23 20:10 UTC, balaji-sivasakthi commented
> A `postinstall` script that build packages could make it works

@gioboa Ok, I will write a custom script and execute through `postinstall`.

functionality should be as follows:
- Build with pnpm build.eslint, pnpm build, then cd packages/qwik-react/ and pnpm build.
- Run pnpm docs.dev.
- Execute scripts based on the directories.

2024-01-23 20:13 UTC, gioboa commented
> > A `postinstall` script that build packages could make it works
> 
> @gioboa Ok, I will write a custom script and execute through `postinstall`.
> 
> functionality should be as follows:
> - Build with pnpm build.eslint, pnpm build, then cd packages/qwik-react/ and pnpm build.
> - Run pnpm docs.dev.
> - Execute scripts based on the directories.
> 

The postinstall script need to do one thing, build all packages and stop.

Then everyone can do whatever they want

2024-01-23 20:16 UTC, balaji-sivasakthi commented
@gioboa Okay, then I will directly execute all the builds, and I won't need to write custom scripts.

2024-01-23 20:27 UTC, balaji-sivasakthi commented
@gioboa     `"postinstall": "pnpm build.full",` Shall add this as postinstall script?

2024-01-23 21:07 UTC, gioboa commented
> @gioboa `"postinstall": "pnpm build.full",` Shall I, add this as postinstall script?

this command will build the rust packages as well 🤔 
`build.local` is enough to solve the website issue

2024-01-24 08:05 UTC, Balastrong approved these changes
Great, thanks @balaji-sivasakthi and @gioboa, it's working now :D

2024-01-24 09:18 UTC, wmertens commented
Actually I have another solution, I'll make the PR shortly.

2024-01-24 16:00 UTC, wmertens commented
Hi @balaji-sivasakthi, this is my version, it runs build.local as well as build.client (for the repl), and it only does it when actually building or running the docs: https://github.com/BuilderIO/qwik/pull/5755/files#diff-9db2b4afcf2ce87ebbe05e607f415aadf7e019c4feb28b2d4fa504d31dabe52b

2024-01-24 17:23 UTC, balaji-sivasakthi commented
@wmertens LGTM

2024-01-24 21:42 UTC, wmertens commented
Ok I'm closing in favor of #5755, but thank you for your efforts!

2024-01-24 21:42 UTC, closed without merging