fix: lock down `@auth/core`
BuilderIO/qwik pull request #5790
Opened 2024-01-27 22:52 UTC by balazsorban44

# Overview

Auth.js author here!

First off, thank you to the Builder.io team for taking interest in maintaining an integration with Auth.js! We are currently working on writing up the base guidelines for third-party integrations, and fully respect if you want to keep maintaining your own package instead of coming over to `@auth/qwik` (happy to collaborate!). I'll remember to send over the guidelines once we have them!

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

To avoid issues like #5783, in this PR I suggest making `@auth/core` a dependency of qwik-auth and lock it down to a version you are committed to maintain. Changes land in `@auth/core` that can still be braking without any warnings, as it's still distributed as experimental.

#5783 was a consequence of this PR https://github.com/nextauthjs/next-auth/pull/9686, which was landed in 0.22.0, so I propose locking down on 0.21.0 for now. Feel free to adjust, if you think you are behind more than this.

Sidenote. This is not included in the PR, but another neat thing we decided to do is sync our providers into `@auth/lib/providers/*`, so user's won't need to install `@auth/core` at all! Check out this script and tweak it if interested! https://github.com/nextauthjs/next-auth/blob/main/packages/utils/scripts/providers.js.

This would likely give a better DX for your users. :wink:

Feel free to reach out for further discussions!

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-01-28 13:11 UTC, gioboa approved these changes
Nice @balazsorban44 Thanks for you help

2024-01-28 13:24 UTC, gioboa requested changes
@balazsorban44 Can you check the failing tests pls?

2024-01-28 20:00 UTC, PatrickJS approved these changes

2024-01-28 20:26 UTC, gioboa approved these changes
🚀

2024-01-28 20:26 UTC, merged

2024-02-01 07:49 UTC, hosseinitabar commented
This is not solved yet. 

With these latest updated:

```
    "devDependencies": {
        "@auth/core": "^0.25.0",
        "@builder.io/partytown": "^0.9.1",
        "@builder.io/qwik": "^1.4.3",
        "@builder.io/qwik-auth": "~0.1.3",
        "@builder.io/qwik-city": "^1.4.3",
        "@tailwindcss/typography": "^0.5.10",
        "@types/compression": "^1.7.5",
        "@types/cors": "^2.8.16",
        "@types/eslint": "^8.56.2",
        "@types/express": "^4.17.21",
        "@types/node": "^20.11.14",
```

We still get this error:

```
DockerContainer | [auth][error] UnknownAction: Cannot parse action at /api/auth/session .Read more at https://errors.authjs.dev#unknownaction
DockerContainer |     at parseActionAndProviderId (file:///Project/Infra/node_modules/@auth/core/lib/utils/web.js:102:15)
DockerContainer |     at toInternalRequest (file:///Project/Infra/node_modules/@auth/core/lib/utils/web.js:32:40)
DockerContainer |     at Module.Auth (file:///Project/Infra/node_modules/@auth/core/index.js:66:35)
DockerContainer |     at getSessionData (/Project/Infra/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:305:50)
DockerContainer |     at onRequest (/Project/Infra/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:244:50)
DockerContainer |     at async Object.next (file:///Project/Infra/node_modules/@builder.io/qwik-city/vite/index.mjs:24840:9)
DockerContainer |     at async runNext (file:///Project/Infra/node_modules/@builder.io/qwik-city/vite/index.mjs:25085:5)
DockerContainer |     at async file:///Project/Infra/node_modules/@builder.io/qwik-city/vite/index.mjs:25653:26
DockerContainer | 7:45:13 AM [vite] Internal server error: 
DockerContainer |       at getSessionData (/Project/Infra/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:320:9)
DockerContainer |       at async onRequest (/Project/Infra/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:241:34)
DockerContainer |       at async Object.next (file:///Project/Infra/node_modules/@builder.io/qwik-city/vite/index.mjs:24840:9)
DockerContainer |       at async runNext (file:///Project/Infra/node_modules/@builder.io/qwik-city/vite/index.mjs:25085:5)
DockerContainer |       at async file:///Project/Infra/node_modules/@builder.io/qwik-city/vite/index.mjs:25653:26

```

For this `Plugin.ts` file:

```
// @ts-nocheck

import { serverAuth$ } from '@builder.io/qwik-auth'
import type { Provider } from '@auth/core/providers'
import Keycloak from '@auth/core/providers/keycloak'

export const { onRequest, useAuthSession, useAuthSignin, useAuthSignout } = serverAuth$(
    ({ env }) => ({
        secret: env.get("AUTH_SECRET"),
        trustHost: true,
        callbacks: {
            async session({
                session,
                token,
            }) {
                session.user.guid = token.sub
                return session
            }
        },
        providers: [
            Keycloak({
                clientId: 'Site',
                clientSecret: env.get('KEYCLOAK_CLIENT_SECRET') as string,
                issuer: env.get('KEYCLOAK_ISSUER') as string
            }),
        ] as Provider[],
    })
);

```

2024-02-03 07:15 UTC, maiieul commented
Hey @balazsorban44 👋

 Just to let you know that we all agreed (@mhevery included) on Discord that it would be great to bring `qwik-auth` over to `@auth/qwik`. I'm full-time on open-source at the moment, building https://qwikui.com/ and more importantly https://github.com/x-ploration-of-mars/x-stack where Auth.js will be the recommended default. So you can count on me to try my best to help you for the migration. I might be lacking some understanding of the Qwik code or the Auth.js code, but I've dived quite a few times into the Qwik and Auth.js codebase in the past, so I hopefully should be able to make myself useful 👀
 
 Feel free to come by on the builder discord when you think auth.js is ready and we can work on that together. The others will probably be able to help me if we ever get stuck ^^.