test(use-visible-task): add more use visible task tests
BuilderIO/qwik pull request #5851
Opened 2024-02-14 18:31 UTC by Varixo

# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

This PR adds more use visible task tests with fixes

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-02-14 18:33 UTC, gioboa commented
@Varixo 👏 great

2024-02-15 17:26 UTC, mhevery requested changes
Great work!  the only issue I seed is the `:` in the `vnode_getProp` function. 

Alos since you are adding `document` and `window` prefix, can we add `v2/use-on.unit.tsx` tests?


Otherwise this looks great!

2024-02-15 17:26 UTC, mhevery commented on packages/qwik/src/core/v2/client/vnode-diff.ts
> +          if (key.startsWith(':') || key.startsWith('document:') || key.startsWith('window:')) {
So this is not right. The code needs to stay as is, which means the code above needs to change.

The way it works now is that any property that starts with `:` is not serializable. 

For example `:onClick$` So i think we need to have `:document:onClick$` or something like that.

2024-02-15 17:26 UTC, mhevery commented on packages/qwik/src/core/v2/client/vnode-diff.ts
> +          let eventName = event.type;
I don't think this is right. See comment bellow about it having to start with `:`

2024-02-19 04:29 UTC, merged